# Cuda image compatible with 18.04
FROM nvidia/cudagl:11.4.2-base-ubuntu18.04
 
# Minimal setup
RUN apt-get update \
 && apt-get install -y locales lsb-release
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg-reconfigure locales
 
# Install ROS melodic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-melodic.list'
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt-get update 
RUN apt-get install -y ros-melodic-desktop-full

# Install mesa utils for glxinfo
RUN apt-get install -y mesa-utils

# Install mesa 21.x+
RUN apt-get -y install software-properties-common
RUN add-apt-repository -y ppa:kisak/kisak-mesa
RUN apt-get update
RUN apt-get -y upgrade

# Copy ned files
COPY /ned_ros /ned_ros

# Additional installations
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
RUN apt-get update -q && \
    apt-get upgrade -yq && \
    apt-get install -yq xauth && \
    apt-get install -yq wget curl git vim sudo && \
    apt-get install -yq ros-melodic-moveit && \
    apt-get install -y ros-melodic-rosbridge-server

RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc

# Add user
RUN useradd -ms /bin/bash container # creates new user with new home directory (the -m option)
USER container

